In [ ]:
#numpy: numerical python
#library used mainly for working with:
#1. data creation (arrays...)
#2. performing mathematical calculations

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np


In [3]:
a=np.array([10,20,30,40])
print (a)

[10 20 30 40]


In [10]:
b=np.array([[20,40],[60,80]])
print (b)
b.shape #displays no of rows and columns
b.ndim #displays dimension
b.size #no of elements
print (b.dtype)

[[20 40]
 [60 80]]
int64


In [11]:
#create array using arange function
c=np.arange(1,6)
c

array([1, 2, 3, 4, 5])

In [12]:
d=np.array([[12,13,24],[14,15,16],[17,18,19]])
print (d)

[[12 13 24]
 [14 15 16]
 [17 18 19]]


In [14]:
#array_name(row specification, column specification)
print (d[0:2,0:2])

[[12 13]
 [14 15]]


In [17]:
#create a 2 d array of four rows and four columns 
array=np.array([[12,13,14,15],[16,17,18,19],[20,21,22,23],[24,25,26,27]])
print (array)
print (array[0:3,1:3])
print (array[0:4,3:4])

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]
[[13 14]
 [17 18]
 [21 22]]
[[15]
 [19]
 [23]
 [27]]


In [18]:
print (array[:,3])
print (array[3,:])

[15 19 23 27]
[24 25 26 27]


In [ ]:
'''algorithms
#to find largest of 3 numbers
step 1: start
step 2: declare three variables a,b and c
step 3: read a,b and c
step 4: if a>c and a>b, display a is largest
step 5: if b>c and b>a, display b is largest
step 6: else display c is largest
step 7: stop'''

In [ ]:
#write an algorithm for the following code
def fact(n):
    if n==0:
        return 1
    else:
        return n*fact(n-1)

In [ ]:
step 1: start
step 2: if n==0, return 1
step 4: else return n* fact(n-1)
step 5: stop

In [1]:
import numpy as np
#original 1d array
r=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print (r)
s=r.reshape(4,3)
print (s)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [2]:
'''create a 2d array of 5 rows and 4 columns
check the shape of the array
check the size of the array
check the dimension of the array
reshape the array
slice the array as you require'''
h=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]])
print (h)
h.size
h.shape
h.ndim
j=h.reshape(4,5)
print (h)
print (h[0:2,0:2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[1 2]
 [5 6]]


In [6]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[3,4,5],[6,7,8]])
result=a@b
result

array([[15, 18, 21],
       [33, 40, 47]])

In [9]:
#write a python program to create two matrices. find the number of dimensions, shape, size
#access the first row and second column of B
#perform matrix addition and multiplication
#reshape the matrices and add them
import numpy as np
a=np.array([[1,3],[5,7]])
a.ndim
a.shape
a.size
b=np.array([[2,4],[6,8]])
b.ndim
b.shape
b.size
print ("First row and second column of B:", b[0:1,1:])
print ("Addition",np.add(a,b))
print ("Multiplication", a@b)
a.reshape(1,4)
print (a)
b.reshape(1,4)
print (b)
print (np.add(a,b))

First row and second column of B: [[4]]
Addition [[ 3  7]
 [11 15]]
Multiplication [[20 28]
 [52 76]]
[[1 3]
 [5 7]]
[[2 4]
 [6 8]]
[[ 3  7]
 [11 15]]


In [ ]:
#write a python program to create an array and perform addition of two matrices

In [ ]:
#broadcasting in numpy
#broad casting is a nupy feature that allows us to perform mathemetical operations on arrays of
#different shapes without manually making their sizes equal

In [10]:
#1D+Scalar
a=np.array([1,2,3,4,5])
print (a+5)

[ 6  7  8  9 10]


In [11]:
#2D array+Scalar
b=np.array([[1,2,3],[4,5,6]])
print (b+5)

[[ 6  7  8]
 [ 9 10 11]]


In [12]:
#matrix+1d array
A=np.array([[1,2,3],[4,5,6]])
B=np.array([7,8,9])
print (A+B)

[[ 8 10 12]
 [11 13 15]]


In [14]:
#Column broadcasting
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[10],[20]])
print(A+B)

[[11 12 13]
 [24 25 26]]


In [15]:
#create 3x3 array of zeros
import numpy as np
a=np.zeros((3,3))
print (a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
#create an array of 4x2 of ones
a=np.ones((4,2))
a

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
#broadcasting is possible in multiplication
A=np.array([[1,2,3],[4,5,6]])
B=np.array([10,20,30])
print ("Element wise multiplication", (A*B))
print (A@B)

Element wise multiplication [[ 10  40  90]
 [ 40 100 180]]
[140 320]


In [ ]:
#create a numpy array [10,20,30,40] and use broadcasting to add 10 to every element
'''create two arrayys, where first array is 2d and second array is 1d. take elements from the user
Increase both the arrays by 5, then add and multiply the arrays'''
#create a 3x3 array numpy matrix containing values from 1 to 9 using broadcasting 

In [2]:
#regular expressions
import re
#match(): only matches at the beginning of a string 
text= "python is easy"
result=re.match("python",text)
print(result)

<re.Match object; span=(0, 6), match='python'>


In [6]:
text= "i like python"
result= re.match("python",text)
print(result)

None


In [7]:
#findall()
txt="The rain in spain"
x=re.findall("ai",txt)
print(x)

['ai', 'ai']


In [31]:
text= "my marks are 75,82, and 91"
result=re.findall("\d", text)
print (result)
result=re.findall("\d+", text)
print (result)

['7', '5', '8', '2', '9', '1']
['75', '82', '91']


In [11]:
#re.sub()=function used to replace matching text
import re
text="i like java"
result=re.sub("java","python",text)
print(result)

i like python


In [18]:
#split()
text= "the rain in spain"
x=re.split("\s",text)
print (x)

['the', 'rain', 'in', 'spain']


In [19]:
text= "the rain in spain"
y=re.split("\s",text,2)
print (y)

['the', 'rain', 'in spain']


C:\Users\Admin\AppData\Local\Temp\ipykernel_12780\1967587098.py:2: DeprecationWarning: 'maxsplit' is passed as positional argument
  y=re.split("\s",text,2)


In [20]:
text="python is one of the easiest programming languages"
result=re.split(r"\s",text)
result

['python', 'is', 'one', 'of', 'the', 'easiest', 'programming', 'languages']

In [21]:
text="python is one of the easiest programming languages"
result=re.split(r"\s",text,4)
result

C:\Users\Admin\AppData\Local\Temp\ipykernel_12780\1244554356.py:2: DeprecationWarning: 'maxsplit' is passed as positional argument
  result=re.split(r"\s",text,4)


['python', 'is', 'one', 'of', 'the easiest programming languages']

In [22]:
#re.search(): checks whether the given pattern is found or not
text="i am learning python"
result=re.search("learning",text)
result

<re.Match object; span=(5, 13), match='learning'>

In [23]:
import re
txt="the rain in spain"
x=re.findall("[a-m]",txt)
print(x)

['h', 'e', 'a', 'i', 'i', 'a', 'i']


In [27]:
import re
txt="The rain in Spain"
x=re.findall("[A-m]",txt)
print(x)

['T', 'h', 'e', 'a', 'i', 'i', 'S', 'a', 'i']


In [32]:
txt="hello planet dfkbg"
x=re.findall("h...o",txt)
x

['hello']

In [2]:
import re
txt="hello planet"
#check if the string starts with hello
x=re.findall("^hello",txt)
if x:
    print("Yes matched")
else:
    print ("No match")

Yes matched


In [3]:
import re
txt="hello planet"
#check if the string ends with planet
x=re.findall("planet$",txt)
if x:
    print ("Yes")
else:
    print("No")

Yes


In [7]:
import re
txt="hello planet, helium,henry"
x=re.findall("he.*",txt)
print(x)
y=re.findall("he.*o", txt)
print (y)

['hello planet, helium,henry']
['hello']


In [11]:
import re
txt="he,hello planet, helium,henry"
x=re.findall("he.+o",txt)
print(x)

['he,hello']


In [16]:
import re
txt="helo,hello planet, helium,henry"
x=re.findall("he.?o",txt)
print(x)

['helo']


In [15]:
import re
txt="hello planet"
x=re.findall("he.(2)o",txt)
print(x)

[]


In [3]:
import re
text="The rain in spain"
#check if the string starts with "The"
x=re.findall("\AThe",text)
if x:
    print ("Yes")
else:
    print("No")

Yes


In [10]:
#(.)=wild character
import re
text="cat cut cot c9t"
result=re.findall(r"c.t",text)#wild character
result1=re.findall(r"c.*t",text)#wild character with *
result2=re.findall(r"c.+",text)#wild character with +
print(result)
print(result1)
print(result2)

['cat', 'cut', 'cot', 'c9t']
['cat cut cot c9t']
['cat cut cot c9t']


In [16]:
import re

text="cat cut cot c9t, ct, cry"
res=re.findall(r"c.+?t",text)#wild character with +
print(res)

['cat', 'cut', 'cot', 'c9t']
